lang: fr
slug: product_management
title: Gestion de produit
subtitle: Scalez votre idée
intro: Notre équipe produit améliore votre logiciel avec des sprints de développement agiles et priorisés en fonction des attentes de vos clients.
description: We are your product team on demand improving your software with agile development sprints strategically prioritized on your customers’ needs.
objective: Development sprints
duration: On demand
