lang: fr
slug: applications-mobiles-natives-hybrides
originalPath: https://www.belighted.com/fr/blog/applications-mobiles-natives-hybrides
title: "Applications SaaS mobiles : faut-il opter pour des applications natives
  ou hybrides ?"
author: Nicolas Jacobeus
description: Votre application SaaS a besoin d'une version mobile.  Vos
  développeurs vous demandent donc si vous voulez une application native ou une
  application hybride. Apprenez les bases grâce à notre framework de
  développement SaaS.
image: ./images/Sans%20titre%20%2813%29-1.png
date: 1577836800000
body: >-
  <p><img
  src="https://www.belighted.com/hs-fs/hubfs/applications-mobiles-natives-hybrides.png?width=1200&amp;name=applications-mobiles-natives-hybrides.png"
  alt="applications-mobiles-natives-hybrides" width="1200" style="width:
  1200px;"
  srcset="https://www.belighted.com/hs-fs/hubfs/applications-mobiles-natives-hybrides.png?width=600&amp;name=applications-mobiles-natives-hybrides.png
  600w,
  https://www.belighted.com/hs-fs/hubfs/applications-mobiles-natives-hybrides.png?width=1200&amp;name=applications-mobiles-natives-hybrides.png
  1200w,
  https://www.belighted.com/hs-fs/hubfs/applications-mobiles-natives-hybrides.png?width=1800&amp;name=applications-mobiles-natives-hybrides.png
  1800w,
  https://www.belighted.com/hs-fs/hubfs/applications-mobiles-natives-hybrides.png?width=2400&amp;name=applications-mobiles-natives-hybrides.png
  2400w,
  https://www.belighted.com/hs-fs/hubfs/applications-mobiles-natives-hybrides.png?width=3000&amp;name=applications-mobiles-natives-hybrides.png
  3000w,
  https://www.belighted.com/hs-fs/hubfs/applications-mobiles-natives-hybrides.png?width=3600&amp;name=applications-mobiles-natives-hybrides.png
  3600w" sizes="(max-width: 1200px) 100vw, 1200px"></p>

  <p>La plupart des créateurs d'applications SaaS se rendent compte qu'ils <strong><a href="https://www.inc.com/rahul-varshneya/saas-businesses-don-t-screw-up-your-mobile-app.html" rel="noopener" target="_blank">doivent développer un équivalent mobile</a></strong> de leur application web, car les utilisateurs souhaitent disposer des mêmes fonctionnalités sur leurs téléphones.</p>

  <!--more-->

  <p>Cependant, il ne suffit pas de rediriger les utilisateurs vers le navigateur de leur téléphone. Une <strong><a href="https://www.nngroup.com/articles/mobile-native-apps/" rel="noopener" target="_blank">application native ou hybride,</a></strong> c'est-à-dire une application conçue pour fonctionner sur un téléphone, est désormais indispensable pour la plupart des <a href="/fr/qu-est-ce-que-le-saas-guide" rel="noopener" target="_blank"><span style="font-weight: bold;">entreprises&nbsp;SaaS</span></a>.</p>

  <p>Lors du développement d'une application pour un <a href="/fr/qu-est-ce-que-le-saas-guide" rel=" noopener"><strong>SaaS</strong></a>, comment choisir entre hybride ou native&nbsp;? Y a-t-il une différence de coût&nbsp;? Poursuivez votre lecture pour plus de détails et pour découvrir notre solution préférée.</p>

  <h2><strong>Différences entre les applications hybrides et natives</strong></h2>

  <p>Une application native est une application que les développeurs créent spécifiquement pour le système d'exploitation d'un téléphone, généralement Android ou iOS. Ils doivent créer une application différente pour chaque plateforme, car elles <strong><a href="https://www.mobiloud.com/blog/native-web-or-hybrid-apps/" rel="noopener" target="_blank">ne fonctionnent pas de la même façon</a></strong>. Bien qu'une application puisse sembler identique sous Android et iOS, il s'agit en fait de deux applications complètement distinctes écrites dans des langages de programmation différents. Par exemple, Pokemon Go, What's App, Gmail et Twitter sont des applications natives.</p>

  <p>Les applications hybrides prennent les fonctionnalités web et les entourent d'une fine couche de développement mobile natif.</p>

  <p>Cette solution peut sembler idéale si vous avez déjà une application web. Il suffit d'ajouter un peu d'iOS ou d'Android autour et voilà, non?</p>

  <p>Une approche hybride apporte de <strong><a href="https://www.clickz.com/the-pros-cons-and-politics-of-hybrid-mobile-apps/93887/" rel="noopener" target="_blank">nombreux avantages</a></strong>, notamment la possibilité de mettre à jour l'application à un seul endroit (la partie web) puis de déployer les changements sur les deux versions en même temps. Les applications purement natives, quant à elles, doivent être mises à jour séparément. (À ce stade, vous êtes probablement déjà en train d'imaginer l'effet sur vos <strong><a href="https://clutch.co/app-developers/resources/cost-build-mobile-app-survey" rel="noopener" target="_blank">coûts</a></strong>&nbsp;!)</p>

  <p><strong>Cependant, il est parfois nécessaire de développer une application spécifique pour un environnement mobile natif.</strong> Philippe, développeur chez Belighted, donne les exemples suivants&nbsp;:</p>

  <ul>

  <li><span style="background-color: transparent;">les applications avec des écrans très personnalisés (comme les jeux)</span></li>

  <li><span style="background-color: transparent;">les applications qui nécessitent un accès spécifique au téléphone (lecteur multimédia, appareil photo, etc.)</span></li>

  <li><span style="background-color: transparent;">les applications qui requièrent un niveau de sécurité élevé (applications bancaires, applications d'authentification)</span></li>

  <li><span style="background-color: transparent;">les applications qui nécessitent une connaissance spécifique du système d'exploitation (applications clavier, composeur de numéros)</span></li>

  </ul>

  <p>Des développeurs de Salesforce ont analysé les avantages et les inconvénients de l'utilisation des technologies web, natives et hybrides pour une application mobile&nbsp;:</p>

  <p><img src="https://www.belighted.com/hs-fs/hubfs/native.png?width=1450&amp;name=native.png" alt="native" width="1450" style="width: 1450px; margin: 0px 0px 4px;" srcset="https://www.belighted.com/hs-fs/hubfs/native.png?width=725&amp;name=native.png 725w, https://www.belighted.com/hs-fs/hubfs/native.png?width=1450&amp;name=native.png 1450w, https://www.belighted.com/hs-fs/hubfs/native.png?width=2175&amp;name=native.png 2175w, https://www.belighted.com/hs-fs/hubfs/native.png?width=2900&amp;name=native.png 2900w, https://www.belighted.com/hs-fs/hubfs/native.png?width=3625&amp;name=native.png 3625w, https://www.belighted.com/hs-fs/hubfs/native.png?width=4350&amp;name=native.png 4350w" sizes="(max-width: 1450px) 100vw, 1450px">[<strong><a href="https://trailhead.salesforce.com/trails/mobile_sdk_intro/modules/mobile_sdk_introduction/units/mobilesdk_intro_scenarios">Source</a></strong>]</p>

  <p>Que vous conceviez une application mobile native ou hybride, vos développeurs voudront travailler avec un framework. Ils disposent ainsi de code prêt à l'emploi qu'ils peuvent intégrer selon leurs besoins.</p>

  <h2><strong>Le framework React Native</strong></h2>

  <p>Il y a un framework qui surpasse les autres&nbsp;: React Native.</p>

  <p><strong>Il offre le meilleur des deux mondes, la capacité de créer de véritables applications natives de façon aussi pratique que si vous développiez des applications pour le web. Cela signifie que vous aurez l'aspect natif et la convivialité des interfaces de la plateforme, la vitesse native, etc.</strong></p>

  <p>Techniquement, ce n'est pas une technologie hybride car le résultat final est une application native, mais les développeurs ne doivent pas créer deux applications différentes. Avec React Native, le développeur écrit du code similaire au code web (en utilisant React et Javascript) et il est transformé en code natif. Avec un outil hybride typique, le développeur écrit du code web qui sera intégré dans un composant «&nbsp;webviewer&nbsp;» natif.</p>

  <h2><strong>Pourquoi nous utilisons React Native et comment vous en bénéficiez&nbsp;?</strong></h2>

  <p><strong>Créer une application mobile avec React Native offre au développeur l'avantage de n'écrire le code qu'une seule fois. Il est ensuite traduit dans les langages natifs iOS et Android.</strong></p>

  <p>Cette approche est très avantageuse. Deux équipes de développement distinctes ne sont pas nécessaires pour les différents systèmes d'exploitation. (Votre équipe de développement web sera peut-être en mesure de gérer l'application mobile puisque React Native a de nombreux points communs avec son homologue web React.) Vous ne devez pas vous soucier des éventuelles différences qui peuvent se retrouver dans chaque application. De plus, le lancement de l'application s'en trouve accéléré, ce qui est très important pour une nouvelle <a href="/fr/qu-est-ce-que-le-saas-guide" rel="noopener" target="_blank"><span style="font-weight: bold;">entreprise&nbsp;SaaS</span></a>.</p>

  <p>L'équipe d'Instagram a réalisé une <strong><a href="https://instagram-engineering.com/react-native-at-instagram-dd828a9a90c7" rel="noopener" target="_blank">expérience</a></strong> sur une partie native de l'application et a découvert qu'elle pouvait proposer de nouvelles fonctionnalités beaucoup plus rapidement. En utilisant React Native, la proportion de code partagé pour certaines fonctionnalités variait de 85 à 99&nbsp;%, ce qui réduisait considérablement le temps nécessaire au développement pour chaque plateforme.</p>

  <h2><strong>React Native est-il la solution parfaite pour votre application mobile SaaS&nbsp;?</strong></h2>

  <p>React Native n'est&nbsp;<strong><a href="https://stxnext.com/blog/2018/01/24/why-use-react-native-your-mobile-app/" rel="noopener" target="_blank">pas un framework 100&nbsp;%&nbsp;natif</a></strong>.</p>

  <p>Cela peut parfois être visible et avoir (ou non) de l'importance pour une application mobile SaaS. Par exemple, sans apporter la moindre modification au framework, le compte de l'utilisateur est stocké dans l'application elle-même, plutôt que dans le système global (si vous avez également une application web, par exemple). React Native rend également un peu plus difficile la distinction entre l'utilisation du Wi-Fi et celle des données mobiles dans des cas où cette distinction peut s'avérer importante. Cependant, grâce à sa flexibilité, vous pouvez ajouter un minimum ou un maximum de code natif pour atteindre vos objectifs.</p>

  <p>Vous devez aussi avoir les bases des langages de programmation natifs iOS et Android.</p>

  <p>Même si les développeurs ne doivent pas avoir autant de connaissances que pour créer une application native pure, «&nbsp;il faut tout de même bien comprendre l'architecture que vous ciblez&nbsp;», explique Philippe. «&nbsp;Par exemple, même si un outil doit être traduit en hébreu, vous devez savoir qu'il s'écrit de droite à gauche et qu'une lettre peut complètement changer la façon dont la précédente est écrite.&nbsp;»</p>

  <p>Si vous envisagez d'utiliser React Native comme framework pour votre application mobile, votre application web doit être créée avec React. Découvrez les raisons pour lesquelles nous apprécions React en tant que langage de programmation front-end.</p>

  <h2><strong>Applications célèbres créées avec React Native</strong></h2>

  <p>React Native dispose d'une communauté Open Source active et croissante de développeurs. Il s'agit d'un élément essentiel lorsque vous choisissez un framework pour votre start-up de SaaS. En effet, vous serez en mesure de trouver plus facilement des développeurs qui maîtrisent votre technologie et ils pourront puiser dans des ressources de haute qualité pour les aider dans leur travail.</p>

  <p>Le framework de développement mobile React Native a beaucoup de grands noms à son actif, ce qui n'est pas surprenant étant donné qu'il a été créé par des développeurs de Facebook. Le géant des réseaux sociaux a créé ReactJS pour son application web, puis React Native pour améliorer ses applications mobiles.</p>

  <p><strong>Voici quelques-unes des entreprises les plus célèbres qui utilisent React Native pour leurs applications mobiles&nbsp;:</strong></p>

  <ul>

  <li>Facebook</li>

  <li><span style="background-color: transparent;">Instagram</span></li>

  <li><span style="background-color: transparent;">Airbnb</span></li>

  <li><span style="background-color: transparent;">Skype</span></li>

  <li><span style="background-color: transparent;">Tesla</span></li>

  <li><span style="background-color: transparent;">Walmart</span></li>

  <li><span style="background-color: transparent;">Uber Eats</span></li>

  </ul>

  <p>De nombreuses start-up de SaaS développent d'abord une application web, puis arrivent à un point où elles savent qu'elles doivent créer une application mobile. Nous faisons en sorte que vous soyez bien positionné lorsque c'est le moment, car nous travaillons avec React pour le front-end de votre application web.</p>

  <p>Vous souhaitez en savoir plus sur <strong><a href="/fr/blog/methode-developpement-produits-saas" rel=" noopener">nos processus</a></strong> pour aider les <a href="/fr/qu-est-ce-que-le-saas-guide" rel="noopener" target="_blank" style="font-weight: bold;">start-up de SaaS</a>&nbsp;de demain à réussir&nbsp;? Abonnez-vous pour recevoir notre blog par e-mail ou <strong><a href="/fr/evaluation-developpement-produit" rel="noopener" target="_blank">envoyez-nous un e-mail</a></strong>.&nbsp;</p>

  <p><!--HubSpot Call-to-Action Code --><span class="hs-cta-wrapper" id="hs-cta-wrapper-9910533f-98e7-4836-a277-f9b2eb95e8b8"><span class="hs-cta-node hs-cta-9910533f-98e7-4836-a277-f9b2eb95e8b8" id="hs-cta-9910533f-98e7-4836-a277-f9b2eb95e8b8"><!--[if lte IE 8]><div id="hs-cta-ie-element"></div><![endif]--><a href="https://cta-redirect.hubspot.com/cta/redirect/1684659/9910533f-98e7-4836-a277-f9b2eb95e8b8"><img class="hs-cta-img" id="hs-cta-img-9910533f-98e7-4836-a277-f9b2eb95e8b8" style="border-width:0px;" src="https://no-cache.hubspot.com/cta/default/1684659/9910533f-98e7-4836-a277-f9b2eb95e8b8.png" alt="Nouveau call-to-action"></a></span></span><!-- end HubSpot Call-to-Action Code --></p>
tags:
  - label: Product development / Continuous Development
    value: product-development-continuous-development
  - label: The Belighted Way
    value: the-belighted-way
  - label: SaaS development
    value: saas-development
